const LOCAL_MODE = ['localhost', '127.0.0.1', '::1'].includes(location.hostname);
const cfg = window.APP_CONFIG;
const state = { tracks: [], filter: 'all', query: '', selected: new Set(), session: JSON.parse(localStorage.getItem('yt-session') || 'null') };
const $ = selector => document.querySelector(selector);
const esc = value => String(value || '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const api = (path, options = {}) => fetch(path, options).then(async r => { if (!r.ok) throw Error(await r.text()); return r.json(); });
const supa = (path, options = {}) => fetch(cfg.supabaseUrl + path, { ...options, headers: { apikey: cfg.supabasePublishableKey, Authorization: `Bearer ${state.session?.access_token || cfg.supabasePublishableKey}`, ...options.headers } }).then(async r => { if (!r.ok) throw Error(await r.text()); return r.json(); });
const duration = seconds => seconds ? `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}` : '';
const size = bytes => bytes ? `${(bytes / 1048576).toFixed(1)} MB` : '';
const mapTrack = t => ({ ...t, title: t.title || 'Untitled', artist: t.artist || 'Unknown artist', format: t.format || 'audio', size: t.file_size || 0, duration: t.duration || 0, url: LOCAL_MODE ? `/api/download/${t.id}` : '' });
function setStatus(message) { $('#status').textContent = message; }
function visible() { const q = state.query.toLowerCase(), cutoff = Date.now() - 30 * 864e5; return state.tracks.filter(t => { const type = state.filter === 'audio' ? t.format !== 'mp4' : state.filter === 'video' ? t.format === 'mp4' : true; const recent = state.filter === 'recent' ? t.downloaded_at && Date.parse(t.downloaded_at) >= cutoff : true; return type && recent && (!q || `${t.title} ${t.artist} ${t.album}`.toLowerCase().includes(q)); }); }
function updateSelectionBar() { const ids = visible().map(t => String(t.id)); $('#selectionBar').hidden = !LOCAL_MODE || !state.selected.size; $('#selectionCount').textContent = `${state.selected.size} selected`; $('#selectAll').checked = !!ids.length && ids.every(id => state.selected.has(id)); }
function render() { const list = visible(); $('#count').textContent = `${list.length} ${list.length === 1 ? 'file' : 'files'}`; $('#empty').hidden = !!list.length; $('#tracks').innerHTML = list.map(t => `<article class="track"><input class="select-track" type="checkbox" data-id="${t.id}" ${state.selected.has(String(t.id)) ? 'checked' : ''} aria-label="Select ${esc(t.title)}"><div class="cover">${t.thumbnail_url ? `<img class="cover" src="${esc(t.thumbnail_url)}" alt="">` : '♪'}</div><div class="track-main"><p class="track-title">${esc(t.title)}</p><p class="track-meta">${esc(t.artist)} · ${esc(t.format.toUpperCase())} ${size(t.size)} ${duration(t.duration) ? '· ' + duration(t.duration) : ''}</p>${LOCAL_MODE && t.file_available ? `<audio class="player" controls preload="none" src="/api/stream/${t.id}"></audio>` : ''}</div>${t.url ? `<a class="download" href="${t.url}" download aria-label="Download ${esc(t.title)}">↓</a>` : ''}${LOCAL_MODE ? `<button class="delete-track" data-id="${t.id}" aria-label="Delete ${esc(t.title)}">×</button>` : ''}</article>`).join(''); document.querySelectorAll('.select-track').forEach(box => box.onchange = () => { box.checked ? state.selected.add(String(box.dataset.id)) : state.selected.delete(String(box.dataset.id)); updateSelectionBar(); }); document.querySelectorAll('.delete-track').forEach(button => button.onclick = () => deleteTrack(button.dataset.id)); updateSelectionBar(); }
async function load() { try { const data = LOCAL_MODE ? await api('/api/tracks') : (state.session ? { tracks: await supa('/rest/v1/tracks?select=*&order=downloaded_at.desc&limit=500') } : { tracks: [] }); state.tracks = data.tracks.map(mapTrack); render(); $('#loadingOverlay').style.display = 'none'; setStatus(`${state.tracks.length} files`); } catch (error) { $('#loadingOverlay').style.display = 'none'; setStatus('Could not connect'); } }
async function deleteTrack(id) { if (!confirm('Delete this file and its database record?')) return; await api(`/api/delete/${id}`, { method: 'POST' }); state.selected.delete(String(id)); load(); }
async function deleteSelected() { const ids = [...state.selected]; if (!ids.length || !confirm(`Delete ${ids.length} selected files and database records?`)) return; await api('/api/delete-bulk', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ids }) }); state.selected.clear(); load(); }
async function queueDownload() { const url = $('#urlInput').value.trim(); if (!url) return $('#downloadMessage').textContent = 'Paste a YouTube URL first.'; const button = $('#downloadButton'); button.disabled = true; $('#downloadMessage').textContent = 'Adding to queue...'; try { await api('/api/download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, format: $('#formatInput').value }) }); $('#urlInput').value = ''; $('#downloadMessage').textContent = 'Queued. Activity will appear above.'; } catch (e) { $('#downloadMessage').textContent = e.message; } finally { button.disabled = false; } }
async function pollStatus() { if (!LOCAL_MODE) return; try { const s = await api('/api/status'); const active = s.active_items || []; const panel = $('#downloadStatus'); panel.hidden = !(active.length || s.queued); $('#activityText').textContent = active.length ? `${active.length} downloading - ${s.queued} queued` : `${s.queued} queued`; $('#activityRows').innerHTML = active.map(i => `<div class="activity-row"><div class="activity-label"><span>${esc(i.title)}</span><span>${Math.round(i.progress || 0)}% ${esc(i.eta || '')}</span></div><div class="activity-bar"><i style="width:${Math.min(100, i.progress || 0)}%"></i></div></div>`).join('') || '<div class="activity-empty">No active downloads.</div>'; } catch { setStatus('Downloader offline'); } }
$('#search').oninput = e => { state.query = e.target.value; render(); }; $('#refresh').onclick = load; $('#downloadButton').onclick = queueDownload; $('#urlInput').onkeydown = e => { if (e.key === 'Enter') queueDownload(); }; $('#selectAll').onchange = e => { visible().forEach(t => e.target.checked ? state.selected.add(String(t.id)) : state.selected.delete(String(t.id))); render(); }; $('#clearSelection').onclick = () => { state.selected.clear(); render(); }; $('#bulkDelete').onclick = deleteSelected; document.querySelectorAll('.filter').forEach(b => b.onclick = () => { document.querySelectorAll('.filter').forEach(x => x.classList.remove('active')); b.classList.add('active'); state.filter = b.dataset.filter; render(); });
if (!LOCAL_MODE) $('#urlInput').closest('.add-card').hidden = true;
load(); pollStatus(); setInterval(() => { pollStatus(); load(); }, 3000);
