const LOCAL_MODE = ['localhost', '127.0.0.1', '::1'].includes(location.hostname);
const cfg = window.APP_CONFIG;
const state = { tracks: [], filter: 'all', query: '', selected: new Set(), session: JSON.parse(localStorage.getItem('yt-session') || sessionStorage.getItem('yt-session') || 'null') };
const TRACK_CACHE = 'yt-track-cache';
const $ = selector => document.querySelector(selector);
if (!$('#rememberMe')) { const remember = document.createElement('label'); remember.className = 'remember'; remember.innerHTML = '<input id="rememberMe" type="checkbox" checked><span>Remember me on this device</span>'; $('#password').after(remember); }
const esc = value => String(value || '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const api = (path, options = {}) => fetch(path, options).then(async r => { if (!r.ok) throw Error(await r.text()); return r.json(); });
const supa = (path, options = {}) => fetch(cfg.supabaseUrl + path, { ...options, headers: { apikey: cfg.supabasePublishableKey, Authorization: `Bearer ${state.session?.access_token || cfg.supabasePublishableKey}`, ...options.headers } }).then(async r => { if (!r.ok) throw Error(await r.text()); return r.json(); });
const duration = seconds => seconds ? `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}` : '';
const size = bytes => bytes ? `${(bytes / 1048576).toFixed(1)} MB` : '';
const mapTrack = t => ({ ...t, title: t.title || 'Untitled', artist: t.artist || 'Unknown artist', format: t.format || 'audio', size: t.file_size || 0, duration: t.duration || 0, url: LOCAL_MODE ? `/api/download/${t.id}` : '' });
async function hydrateCloudTrack(track) { if (LOCAL_MODE || !track.file_path || !state.session) return track; const cached = JSON.parse(localStorage.getItem(TRACK_CACHE) || '[]').find(item => String(item.id) === String(track.id)); try { const path = encodeURIComponent(track.file_path).replace(/%2F/g, '/'); const signed = await supa(`/storage/v1/object/sign/music/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expiresIn: 604800 }) }); const raw = signed.signedURL || ''; const normalized = raw.startsWith('http') ? raw : `${cfg.supabaseUrl}${raw.startsWith('/storage/v1/') ? raw : `/storage/v1${raw.startsWith('/') ? raw : `/${raw}`}`}`; return { ...track, url: normalized }; } catch { return cached?.url ? { ...track, url: cached.url } : track; } }
function setStatus(message) { $('#status').textContent = message; }
function visible() { const q = state.query.toLowerCase(), cutoff = Date.now() - 30 * 864e5; return state.tracks.filter(t => { const type = state.filter === 'audio' ? t.format !== 'mp4' : state.filter === 'video' ? t.format === 'mp4' : true; const recent = state.filter === 'recent' ? t.downloaded_at && Date.parse(t.downloaded_at) >= cutoff : true; return type && recent && (!q || `${t.title} ${t.artist} ${t.album}`.toLowerCase().includes(q)); }); }
let offlineObjectUrl = '';
async function playableUrl(track) {
  if (!track?.url) return '';
  if (navigator.onLine) return track.url;
  try {
    const cached = await caches.match(track.url, { cacheName: 'downloads-media-v1' });
    if (!cached) return '';
    if (offlineObjectUrl) URL.revokeObjectURL(offlineObjectUrl);
    offlineObjectUrl = URL.createObjectURL(await cached.blob());
    return offlineObjectUrl;
  } catch { return ''; }
}
function updateSelectionBar() { const ids = visible().map(t => String(t.id)); $('#selectionBar').hidden = !LOCAL_MODE || !state.selected.size; $('#selectionCount').textContent = `${state.selected.size} selected`; $('#selectAll').checked = !!ids.length && ids.every(id => state.selected.has(id)); }
async function playTrack(id) { const track = state.tracks.find(item => String(item.id) === String(id)); if (!track?.url) return setStatus('File unavailable'); state.playbackId = String(id); const player = $('#mainPlayer'); player.pause(); player.removeAttribute('src'); player.load(); player.src = track.url; $('#playerTitle').textContent = track.title; $('#playerArtist').textContent = track.artist; $('#playerBar').hidden = false; $('#togglePlayer').textContent = 'Ⅱ'; $('#togglePlayer').setAttribute('aria-label', 'Pause'); setStatus('Loading audio…'); player.load(); try { await player.play(); setStatus(`Playing ${track.title}`); } catch (error) { $('#togglePlayer').textContent = '▶'; $('#togglePlayer').setAttribute('aria-label', 'Play'); setStatus('Audio could not start — tap play'); } }
function playbackList() { return visible().filter(t => t.url); } async function stepTrack(direction) { const list = playbackList(); if (!list.length) return; let index = list.findIndex(t => String(t.id) === String(state.playbackId)); if (index < 0) index = direction > 0 ? -1 : 0; if (state.shuffle) index = Math.floor(Math.random() * list.length); else index = (index + direction + list.length) % list.length; await playTrack(list[index].id); } function togglePlayer() { const player = $('#mainPlayer'); if (player.paused) { player.play().then(() => { $('#togglePlayer').textContent = 'Ⅱ'; $('#togglePlayer').setAttribute('aria-label', 'Pause'); }).catch(() => setStatus('Audio could not start')); } else { player.pause(); $('#togglePlayer').textContent = '▶'; $('#togglePlayer').setAttribute('aria-label', 'Play'); } }
$('#mainPlayer').addEventListener('error', () => setStatus('Audio file could not be loaded')); $('#mainPlayer').addEventListener('playing', () => { $('#togglePlayer').textContent = 'Ⅱ'; $('#togglePlayer').setAttribute('aria-label', 'Pause'); }); $('#mainPlayer').addEventListener('pause', () => { $('#togglePlayer').textContent = '▶'; $('#togglePlayer').setAttribute('aria-label', 'Play'); }); $('#mainPlayer').addEventListener('timeupdate', () => { const p = $('#mainPlayer'); $('#seekBar').value = p.duration ? (p.currentTime / p.duration) * 100 : 0; }); $('#mainPlayer').addEventListener('ended', () => state.repeat ? playTrack(state.playbackId) : stepTrack(1));
function render() { const list = visible(); $('#count').textContent = `${list.length} ${list.length === 1 ? 'file' : 'files'}`; $('#empty').hidden = !!list.length; $('#tracks').innerHTML = list.map(t => `<article class="track"><input class="select-track" type="checkbox" data-id="${t.id}" ${state.selected.has(String(t.id)) ? 'checked' : ''} aria-label="Select ${esc(t.title)}"><div class="cover">${t.thumbnail_url ? `<img class="cover" src="${esc(t.thumbnail_url)}" alt="">` : '♫'}</div><div class="track-main"><p class="track-title">${esc(t.title)}</p><p class="track-meta">${esc(t.artist)} · ${esc(t.format.toUpperCase())} ${size(t.size)} ${duration(t.duration) ? '· ' + duration(t.duration) : ''}</p>${LOCAL_MODE && t.file_available ? `<audio class="player" controls preload="none" src="/api/stream/${t.id}"></audio>` : ''}</div>${t.url ? `<button class="play-track" data-play="${t.id}" aria-label="Play ${esc(t.title)}">▶</button><a class="download" href="${t.url}" download aria-label="Download ${esc(t.title)}">↓</a>` : ''}${LOCAL_MODE ? `<button class="delete-track" data-id="${t.id}" aria-label="Delete ${esc(t.title)}">×</button>` : ''}</article>`).join(''); document.querySelectorAll('.select-track').forEach(box => box.onchange = () => { box.checked ? state.selected.add(String(box.dataset.id)) : state.selected.delete(String(box.dataset.id)); updateSelectionBar(); }); document.querySelectorAll('.delete-track').forEach(button => button.onclick = () => deleteTrack(button.dataset.id)); document.querySelectorAll('[data-play]').forEach(button => button.onclick = () => playTrack(button.dataset.play)); updateSelectionBar(); }
async function load() { try { if (!LOCAL_MODE && !state.session) { state.tracks = []; render(); $('#cloudNotice').hidden = false; $('#empty').hidden = true; $('#loadingOverlay').style.display = 'none'; setStatus('Sign in required'); return; } const data = LOCAL_MODE ? await api('/api/tracks') : { tracks: await supa('/rest/v1/tracks?select=*&order=downloaded_at.desc&limit=500') }; state.tracks = await Promise.all(data.tracks.map(mapTrack).map(hydrateCloudTrack)); if (!LOCAL_MODE) localStorage.setItem(TRACK_CACHE, JSON.stringify(state.tracks)); $('#cloudNotice').hidden = true; render(); $('#loadingOverlay').style.display = 'none'; setStatus(`${state.tracks.length} files`); } catch (error) { const cached = !LOCAL_MODE ? JSON.parse(localStorage.getItem(TRACK_CACHE) || '[]') : []; if (cached.length) { state.tracks = cached; $('#cloudNotice').hidden = true; render(); setStatus(`${cached.length} files · offline`); } else setStatus('Could not connect'); $('#loadingOverlay').style.display = 'none'; } }
async function deleteTrack(id) { if (!confirm('Delete this file and its database record?')) return; await api(`/api/delete/${id}`, { method: 'POST' }); state.selected.delete(String(id)); load(); }
async function deleteSelected() { const ids = [...state.selected]; if (!ids.length || !confirm(`Delete ${ids.length} selected files and database records?`)) return; await api('/api/delete-bulk', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ids }) }); state.selected.clear(); load(); }
async function queueDownload() { const url = $('#urlInput').value.trim(); if (!url) return $('#downloadMessage').textContent = 'Paste a YouTube URL first.'; const button = $('#downloadButton'); button.disabled = true; $('#downloadMessage').textContent = 'Adding to queue...'; try { await api('/api/download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, format: $('#formatInput').value }) }); $('#urlInput').value = ''; $('#downloadMessage').textContent = 'Queued. Activity will appear above.'; } catch (e) { $('#downloadMessage').textContent = e.message; } finally { button.disabled = false; } }
async function signIn(event) { event.preventDefault(); const button = $('#authForm .primary'); button.disabled = true; $('#authMessage').textContent = 'Signing in...'; try { const session = await supa('/auth/v1/token?grant_type=password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: $('#email').value.trim(), password: $('#password').value }) }); state.session = session; localStorage.setItem('yt-session', JSON.stringify(session)); if (LOCAL_MODE) { $('#authMessage').textContent = 'Signed in. Syncing your local library...'; const result = await api('/api/cloud-sync', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session }) }); $('#authDialog').close(); setStatus(`${result.uploaded} files synced`); } else { $('#authDialog').close(); } $('#authMessage').textContent = ''; await load(); } catch (error) { $('#authMessage').textContent = error.message || 'Sign in failed. Check your Supabase Auth email and password.'; } finally { button.disabled = false; } }
function openSignIn() { $('#authMessage').textContent = ''; $('#authDialog').showModal(); }
$('#togglePlayer').onclick = togglePlayer; $('#previousTrack').onclick = () => stepTrack(-1); $('#nextTrack').onclick = () => stepTrack(1); $('#shuffleTrack').onclick = e => { state.shuffle = !state.shuffle; e.currentTarget.setAttribute('aria-pressed', String(state.shuffle)); e.currentTarget.classList.toggle('active', state.shuffle); }; $('#repeatTrack').onclick = e => { state.repeat = !state.repeat; e.currentTarget.setAttribute('aria-pressed', String(state.repeat)); e.currentTarget.classList.toggle('active', state.repeat); }; $('#seekBar').oninput = e => { const player = $('#mainPlayer'); if (player.duration) player.currentTime = (Number(e.target.value) / 100) * player.duration; };
$('#search').oninput = e => { state.query = e.target.value; render(); }; $('#refresh').onclick = load; $('#accountButton').onclick = openSignIn; $('#closeAuth').onclick = () => $('#authDialog').close(); $('#authForm').onsubmit = signIn; $('#signInButton').onclick = openSignIn; $('#downloadButton').onclick = queueDownload; const offlineButton = $('#offlineButton'); if (localStorage.getItem('yt-offline-ready') === '1') offlineButton.textContent = 'Offline saved'; offlineButton.onclick = async () => { const playable = state.tracks.filter(t => t.url); if (!playable.length) return setStatus('No playable files to cache'); offlineButton.disabled = true; setStatus(`Caching ${playable.length} file${playable.length === 1 ? '' : 's'} for offline…`); const cacheOne = async url => { try { const cache = await caches.open('downloads-media-v1'); const response = await fetch(url, { cache: 'reload' }); if (!response.ok) return false; await cache.put(url, response.clone()); return true; } catch { return false; } }; const results = await Promise.all(playable.map(t => cacheOne(t.url))); const saved = results.filter(Boolean).length; if (saved) { localStorage.setItem('yt-offline-ready', '1'); offlineButton.textContent = saved === playable.length ? 'Offline saved' : 'Offline partial'; } setStatus(`${saved}/${playable.length} files cached for offline`); offlineButton.disabled = false; }; $('#urlInput').onkeydown = e => { if (e.key === 'Enter') queueDownload(); }; $('#selectAll').onchange = e => { visible().forEach(t => e.target.checked ? state.selected.add(String(t.id)) : state.selected.delete(String(t.id))); render(); }; $('#clearSelection').onclick = () => { state.selected.clear(); render(); }; $('#bulkDelete').onclick = deleteSelected; document.querySelectorAll('.filter').forEach(b => b.onclick = () => { document.querySelectorAll('.filter').forEach(x => x.classList.remove('active')); b.classList.add('active'); state.filter = b.dataset.filter; render(); }); window.addEventListener('online', () => { setStatus(`${state.tracks.length} files · online`); load(); }); window.addEventListener('offline', () => setStatus(`${state.tracks.length} files · offline`));
$('#authForm').addEventListener('submit', () => { if (!$('#rememberMe').checked) setTimeout(() => { const session = localStorage.getItem('yt-session'); if (session) { sessionStorage.setItem('yt-session', session); localStorage.removeItem('yt-session'); } }, 0); }, true);
async function pollStatus() { if (!LOCAL_MODE) return; try { const s = await api('/api/status'); const active = s.active_items || [], queued = s.queued_items || []; const panel = $('#downloadStatus'); panel.hidden = !(active.length || queued.length); $('#activityText').textContent = active.length ? `${active.length} downloading · ${queued.length} queued` : `${queued.length} queued`; $('#activityRows').innerHTML = [...active.map(i => `<div class="activity-row"><div class="activity-label"><span>${esc(i.title)}</span><span>${Math.round(i.progress || 0)}% ${esc(i.eta || '')}</span></div><div class="activity-bar"><i style="width:${Math.min(100, i.progress || 0)}%"></i></div></div>`), ...queued.map(i => `<div class="activity-row queued"><div class="activity-label"><span>${esc(i.title)}</span><button class="queue-remove" data-queue-url="${esc(i.url)}" type="button">Remove</button></div><span class="queue-state">Queued</span></div>`)].join('') || '<div class="activity-empty">No active downloads.</div>'; $('#stopDownloads').hidden = !(active.length || queued.length); document.querySelectorAll('.queue-remove').forEach(button => button.onclick = async () => { button.disabled = true; await api('/api/stop-one', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: button.dataset.queueUrl }) }); await pollStatus(); }); } catch { setStatus('Downloader offline'); } }
$('#stopDownloads').onclick = async () => { $('#stopDownloads').disabled = true; try { const result = await api('/api/stop', { method: 'POST' }); setStatus(`${result.cancelled || 0} queued downloads stopped`); await pollStatus(); } finally { $('#stopDownloads').disabled = false; } };
const networkPlayTrack = playTrack;
playTrack = async function (id) {
  const track = state.tracks.find(item => String(item.id) === String(id));
  if (navigator.onLine) return networkPlayTrack(id);
  const source = await playableUrl(track);
  if (!source) return setStatus('Not saved for offline use');
  const player = $('#mainPlayer'); player.pause(); player.src = source; player.load(); state.playbackId = String(id);
  $('#playerTitle').textContent = track.title; $('#playerArtist').textContent = track.artist; $('#playerBar').hidden = false; setStatus('Loading offline audio…');
  try { await player.play(); setStatus(`Playing ${track.title}`); } catch { setStatus('Tap play to start offline audio'); }
};
offlineButton.onclick = async () => {
  const playable = state.tracks.filter(t => t.url);
  if (!playable.length) return setStatus('No playable files to cache');
  offlineButton.disabled = true;
  try { if (navigator.storage?.persist) await navigator.storage.persist(); } catch {}
  const cache = await caches.open('downloads-media-v1');
  let saved = 0;
  for (const track of playable) {
    setStatus(`Saving offline ${saved + 1}/${playable.length}…`);
    try {
      const response = await fetch(track.url, { cache: 'reload' });
      if (response.ok) { await cache.put(track.url, response.clone()); saved += 1; }
    } catch { /* keep saving the remaining tracks */ }
  }
  if (saved) { localStorage.setItem('yt-offline-ready', '1'); offlineButton.textContent = saved === playable.length ? 'Offline saved' : 'Offline partial'; }
  setStatus(`${saved}/${playable.length} files cached for offline`);
  offlineButton.disabled = false;
};
if ('mediaSession' in navigator) {
  $('#mainPlayer').addEventListener('playing', () => { const track = state.tracks.find(item => String(item.id) === String(state.playbackId)); if (track) navigator.mediaSession.metadata = new MediaMetadata({ title: track.title, artist: track.artist || 'Unknown artist', album: track.album || 'Downloads' }); });
  const mediaAction = (action, handler) => { try { navigator.mediaSession.setActionHandler(action, handler); } catch {} };
  mediaAction('play', () => togglePlayer()); mediaAction('pause', () => togglePlayer());
  mediaAction('previoustrack', () => stepTrack(-1)); mediaAction('nexttrack', () => stepTrack(1));
}
document.addEventListener('click', async event => {
  const link = event.target.closest?.('a.download');
  if (!link || !link.href) return;
  event.preventDefault();
  link.setAttribute('aria-busy', 'true');
  try {
    const response = navigator.onLine ? await fetch(link.href) : await caches.match(link.href, { cacheName: 'downloads-media-v1' });
    if (!response || !response.ok) throw Error('download failed');
    const objectUrl = URL.createObjectURL(await response.blob());
    const save = document.createElement('a'); save.href = objectUrl; save.download = link.getAttribute('download') || 'music-download'; save.click();
    setTimeout(() => URL.revokeObjectURL(objectUrl), 1000);
  } catch { window.location.href = link.href; }
  finally { link.removeAttribute('aria-busy'); }
});
if (!LOCAL_MODE) $('#urlInput').closest('.add-card').hidden = true;
load(); setTimeout(() => { if (!LOCAL_MODE && !navigator.onLine && !state.session) { const cached = JSON.parse(localStorage.getItem(TRACK_CACHE) || '[]'); if (cached.length) { state.tracks = cached; $('#cloudNotice').hidden = true; render(); setStatus(`${cached.length} files · offline`); } } }, 0); pollStatus(); setInterval(() => { pollStatus(); if (LOCAL_MODE) load(); }, 3000);
